---
  - name: Установка пакета kibana
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.15.1-amd64.deb"

  - name: Копируем конфигурационный файл kibana
    template:
      src: /home/vboxuser/Рабочий стол/NetologyDiplom/ansible/roles/kibana/kibana.j2
      dest: /etc/kibana/kibana.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name:  Перезапускаем kibana и добавляем в автозагрузку
    service:
      name: kibana
      state: restarted
      enabled: yes
