---
  - name: Устанавливаем filebeat
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.15.1-amd64.deb"

  - name: Копируем конфиг filebeat
    template:
      src: /home/vboxuser/Рабочий стол/NetologyDiplom/ansible/roles/filebeat/filebeat.j2
      #src: "{% if ansible_default_ipv4.address == '10.10.1.3' %}filebeat_zone_a.j2{% else %}filebeat_zone_b.j2{% endif %}"
      dest: /etc/filebeat/filebeat.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name: Перезапускаем filebeat и добавляем в автозагрузку
    service:
      name: filebeat
      state: restarted
      enabled: yes
